feat: allow all browserslist options via JS API
browserslist/browserslist-useragent-regexp pull request #1489
Opened 2023-06-16 14:16 UTC by steverep

Fixes #1484 by allowing the JS API to pass any non-regex option to `browserslist`.  I implemented this in a way that is both backwards compatible and doesn't require knowledge of the `browserslist` options.

This doesn't implement for the CLI as the current `env` and `path` options aren't possible there either and doing so requires listing out all the `browserslist` options.

2023-06-16 14:50 UTC, dangreen requested changes
Thanks for the PR!

2023-06-16 14:50 UTC, dangreen commented on src/useragentRegex/useragentRegex.ts
> +  const versionedRegexes = applyVersionsToRegexes(sourceRegexes, regexpOptions)
Let's make code more easer

```ts
export function getPreUserAgentRegexes(options: UserAgentRegexOptions = {}) {
  const finalOptions = {
    ...defaultOptions,
    ...options
  }
  const browsersList = getBrowsersList(finalOptions)
  const mergedBrowsers = mergeBrowserVersions(browsersList)
  const sourceRegexes = getRegexesForBrowsers(mergedBrowsers, finalOptions)
  const versionedRegexes = applyVersionsToRegexes(sourceRegexes, finalOptions)

  return versionedRegexes
}
```

2023-06-16 20:37 UTC, dangreen approved these changes

2023-06-16 20:40 UTC, merged

2023-06-16 20:45 UTC, dangreen commented
@steverep Thanks!

https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v4.1.0

2023-06-19 05:55 UTC, eliasaadeh reviewed
0x1AFc752808fe62BBC62Eaf30105e34b6582e05ba